var greeting =
    '{"learning_1_greeting": '
    '['
    '{'
    '"question_id": "greeting_1",'
    ' "question_type": "text", '
    ' "title": "Nnọọ",'
    ' "subtitle": "Welcome",'
    ' "hint" : "Nnóó"'
    '},'
    '{'
    '"question_id": "greeting_2",'
    ' "question_type": "text", '
    ' "title": "Utụtụ ọma",'
    ' "subtitle": "Good Morning",'
    ' "hint" : "Ūtútú òmá"'
    '},'
    '{'
    '"question_id": "greeting_3",'
    ' "question_type": "text", '
    ' "title": "Heloo",'
    ' "subtitle": "Hello",'
    ' "hint" : "Hēlóó"'
    '},'
    '{'
    '"question_id": "greeting_4",'
    ' "question_type": "text", '
    ' "title": "Kedụ ka ị dị?",'
    ' "subtitle": "How are you",'
    ' "hint" : "Kédū ka í dí"'
    '},'
    '{'
    '"question_id": "greeting_5",'
    ' "question_type": "text", '
    ' "title": "Abali ọma",'
    ' "subtitle": "Good night",'
    ' "hint" : "Ábālì òmá"'
    '},'
    '{'
    '"question_id": "greeting_6",'
    ' "question_type": "text", '
    ' "title": "Good bye",'
    ' "subtitle": "Mgbasa ọma",'
    ' "hint" : "Mgbàsá òmá"'
    '}'
    ']'
    '}';


var phrases =
    '{"learning_2_phrases": '
    '['
    '{'
    '"question_id": "phrase_1",'
    ' "question_type": "text", '
    ' "title": "Biko",'
    ' "subtitle": "Please",'
    ' "hint" : "Bīkó"'
    '},'
    '{'
    '"question_id": "phrase_2",'
    ' "question_type": "text", '
    ' "title": "Mbaa",'
    ' "subtitle": "No",'
    ' "hint" : "Mbáá"'
    '},'
    '{'
    '"question_id": "phrase_3",'
    ' "question_type": "text", '
    ' "title": "Ee",'
    ' "subtitle": "Yes",'
    ' "hint" : "Éé"'
    '},'
    '{'
    '"question_id": "phrase_4",'
    ' "question_type": "text", '
    ' "title": "Chara m",'
    ' "subtitle": "Excuse me",'
    ' "hint" : "Chárá m"'
    '},'
    '{'
    '"question_id": "phrase_5",'
    ' "question_type": "text", '
    ' "title": "Ọ dị m mwute",'
    ' "subtitle": "I am sorry",'
    ' "hint" : "Ō dí m mwūté"'
    '},'
    '{'
    '"question_id": "phrase_6",'
    ' "question_type": "text", '
    ' "title": "Ikekwe",'
    ' "subtitle": "Maybe",'
    ' "hint" : "Íkékwe"'
    '}'
    ']'
    '}';


var foods =
    '{"learning_3_foods": '
    '['
    '{'
    '"question_id": "food_1",'
    ' "question_type": "text", '
    ' "title": "Achicha",'
    ' "subtitle": "Bread",'
    ' "hint" : "Áchichá"'
    '},'
    '{'
    '"question_id": "food_2",'
    ' "question_type": "text", '
    ' "title": "Agwa",'
    ' "subtitle": "Beans",'
    ' "hint" : "Ágwá"'
    '},'
    '{'
    '"question_id": "food_3",'
    ' "question_type": "text", '
    ' "title": "Anu",'
    ' "subtitle": "Meat",'
    ' "hint" : "Ánū"'
    '},'
    '{'
    '"question_id": "food_4",'
    ' "question_type": "text", '
    ' "title": "Mmanu",'
    ' "subtitle": "Oil",'
    ' "hint" : "Mmánū"'
    '},'
    '{'
    '"question_id": "food_5",'
    ' "question_type": "text", '
    ' "title": "Nnu",'
    ' "subtitle": "Salt",'
    ' "hint" : "Ńnū"'
    '},'
    '{'
    '"question_id": "food_6",'
    ' "question_type": "text", '
    ' "title": "Ofe",'
    ' "subtitle": "Soup",'
    ' "hint" : "Sóūp"'
    '}'
    ']'
    '}';


var numbers =
    '{"learning_4_numbers": '
    '['
    '{'
    '"question_id": "numbers_1",'
    ' "question_type": "text", '
    ' "title": "Efu",'
    ' "subtitle": "Zero",'
    ' "hint" : "Éfū"'
    '},'
    '{'
    '"question_id": "numbers_2",'
    ' "question_type": "text", '
    ' "title": "Otụ",'
    ' "subtitle": "One",'
    ' "hint" : "Ōtū"'
    '},'
    '{'
    '"question_id": "numbers_3",'
    ' "question_type": "text", '
    ' "title": "Abụọ",'
    ' "subtitle": "Two",'
    ' "hint" : "Ábūó"'
    '},'
    '{'
    '"question_id": "numbers_4",'
    ' "question_type": "text", '
    ' "title": "Atọ",'
    ' "subtitle": "Three",'
    ' "hint" : "Átó"'
    '},'
    '{'
    '"question_id": "numbers_5",'
    ' "question_type": "text", '
    ' "title": "Anọ",'
    ' "subtitle": "Four",'
    ' "hint" : "Ánó"'
    '},'
    '{'
    '"question_id": "numbers_6",'
    ' "question_type": "text", '
    ' "title": "Ise",'
    ' "subtitle": "Five",'
    ' "hint" : "Ísé"'
    '}'
    ']'
    '}';


var time =
    '{"learning_5_time": '
    '['
    '{'
    '"question_id": "time_1",'
    ' "question_type": "text", '
    ' "title": "Utụtụ",'
    ' "subtitle": "Morning",'
    ' "hint" : "Ūtútú"'
    '},'
    '{'
    '"question_id": "time_2",'
    ' "question_type": "text", '
    ' "title": "Ehihie",'
    ' "subtitle": "Afternoon",'
    ' "hint" : "Éhīhīé"'
    '},'
    '{'
    '"question_id": "time_3",'
    ' "question_type": "text", '
    ' "title": "Etiti abalị",'
    ' "subtitle": "Midnight",'
    ' "hint" : "Étītī ábālì"'
    '},'
    '{'
    '"question_id": "time_4",'
    ' "question_type": "text", '
    ' "title": "Etiti Ehihie",'
    ' "subtitle": "Noon",'
    ' "hint" : "Étītī Éhīhīé"'
    '},'
    '{'
    '"question_id": "time_5",'
    ' "question_type": "text", '
    ' "title": "Ugbua",'
    ' "subtitle": "Now",'
    ' "hint" : "Ūgbūá"'
    '},'
    '{'
    '"question_id": "time_6",'
    ' "question_type": "text", '
    ' "title": "Emechaa",'
    ' "subtitle": "Later",'
    ' "hint" : "Émēcháá"'
    '}'
    ']'
    '}';